services:
  - type: web
    name: tool-summarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - #key: OPENAI_API_KEY
        key: HUGGINGFACE_API_TOKEN
        sync: false  # Set this in the Render dashboard manually